---
- name: Install any necessary dependencies [Debian/Ubuntu]
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - curl
    - python-httplib2

- name: Download influxdb-data package via URL [Debian/Ubuntu]
  command: curl -o /tmp/influxdb-data-ansible-download.deb {{ influxdb_data_install_url }}
  when: influxdb_data_install_url is defined and influxdb_data_install_url != None

- name: Install downloaded influxdb-data package [Debian/Ubuntu]
  apt:
    deb: /tmp/influxdb-data-ansible-download.deb
    state: present
  when: influxdb_data_install_url is defined and influxdb_data_install_url != None
