---
- include: install.yml
  tags: [influxdb-data, install]

- include: configure.yml
  tags: [influxdb-data, configure]

- name: Start the influxdb-data service
  service:
    name: influxdb
    state: restarted
    enabled: yes
  register: influx_data_started
  when: influx_data_start_service

- name: Wait for influxdb-data to come up
  wait_for:
    host: "{{ influx_data_http_bind_address_hostname | default(\"localhost\", true) }}"
    port: "{{ influx_data_http_bind_address_port }}"
    delay: 1
    timeout: 5
  when: influx_data_started.changed and influx_data_start_service
  ignore_errors: yes
  register: influx_data_start_attempt

- name: Run tail on log
  command: tail /var/log/influxdb/influxd.log
  register: influx_data_tail_output
  when: influx_data_start_attempt.failed is defined and influx_data_start_attempt.failed == True

- name: Show log output
  debug:
    msg: "{{ influx_data_tail_output.stdout_lines }}"
  when: influx_data_start_attempt.failed is defined and influx_data_start_attempt.failed == True

- name: Assert status of influxdb-data service
  assert:
    that:
      - "influx_data_start_attempt == 0"
  when: influx_data_started.changed and influx_data_start_service and influx_data_start_attempt.failed is defined and influx_data_start_attempt.failed == True

# FIXME: Don't hard-code port 8091
- name: Capture current cluster status
  uri:
    url: http://localhost:8091/show-cluster
  register: influx_data_show_cluster

# FIXME: Don't hard-code port 8088
- name: Add data nodes to cluster (run from first meta node)
  command: influxd-ctl add-data {{ item }}:8088
  when: "'{{ item }}:8088' not in influx_data_show_cluster['json']['data']|map(attribute='addr')|list"
  with_items: "{{ groups.data }}"
  delegate_to: "{{ groups.meta[0] }}"
