---
- name: Set configuration directory path
  file:
    path: "{{ influxdb_meta_configuration_dir }}"
    state: directory

- name: Set templatized influxdb-meta configuration
  template: 
    src: influxdb-meta.conf.j2 
    dest: "{{ influxdb_meta_configuration_dir }}/influxdb-meta.conf"
    force: yes
    backup: yes
    owner: influxdb
    group: influxdb
    mode: 0744
  when: influxdb_meta_template_configuration

- name: Overwrite hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: is_vagrant or influxdb_meta_overwrite_hosts
  
- name: Stop firewalld [local testing only]
  service:
      name: firewalld
      state: stopped
  when: is_vagrant and ansible_distribution == 'CentOS'
