---
- include: install.yml
  tags: [influxdb-meta, install]

- include: configure.yml
  tags: [influxdb-meta, configure]

- name: Start the influxdb-meta service
  service:
    name: influxdb-meta
    state: restarted
    enabled: yes
  register: influxdb_meta_started
  when: influxdb_meta_start_service

- name: Wait for influxdb-meta to come up
  wait_for:
    host: "{{ influxdb_meta_http_bind_address_hostname | default(\"localhost\", true) }}"
    port: "{{ influxdb_meta_http_bind_address_port }}"
    delay: 1
    timeout: 5
  when: influxdb_meta_started.changed and influxdb_meta_start_service
  ignore_errors: yes
  register: influxdb_meta_start_attempt

- name: Assert status of influxdb-meta service
  assert:
    that:
      - "influxdb_start_attempt == 0"
  when: influxdb_meta_started.changed and influxdb_meta_start_service and influxdb_meta_start_attempt.failed is defined and influxdb_meta_start_attempt.failed == True

# FIXME: Don't hard-code port 8091
- name: Capture current cluster status
  uri:
    url: http://localhost:8091/show-cluster
  register: influxdb_meta_show_cluster

# FIXME: Don't hard-code port 8091
- name: Add meta nodes to cluster (run from first meta node)
  command: influxd-ctl add-meta {{ item }}:8091
  when: "'{{ item }}:8091' not in influxdb_meta_show_cluster['json']['meta']|map(attribute='addr')|list"
  with_items: "{{ groups.meta }}"
  delegate_to: "{{ groups.meta[0] }}"
